export interface Theme {
  document: string
  document2: string
  document3: string
  onDocument: string
  onDocument2: string
  onDocument3: string
  onDocumentHighlight: string
  navigation: string
  onNavigation: string
  subNavigation: string
  onSubNavigation: string
  button: string
  buttonHover: string
  buttonDisabled: string
  button2: string
  button2Hover: string
  button2Disabled: string
  onButton: string
  input: string
  inputBorder: string
  onInput: string
  divider: string
  main: string
  onMain: string
  card: string
  onCard: string
  success: string
  onSuccess: string
  warning: string
  onWarning: string
  error: string
  onError: string
  teaser: string
  onTeaser: string
  touchableHighlight: string
}
