export const API_CODE = {
  status: 'status',
  errors: 'errors',
  ERROR: 'ERROR',
  OK: 'OK',
  ERROR_NOT_FOUND: 'ERROR_NOT_FOUND',
  ERROR_INVALID_JSON: 'ERROR_INVALID_JSON',
  ERROR_INVALID_EMAIL: 'ERROR_INVALID_EMAIL',
  ERROR_EMPTY_WORKER_LIST: 'ERROR_EMPTY_WORKER_LIST',
  ERROR_EMPTY_TITLE: 'ERROR_EMPTY_TITLE',
  ERROR_TITLE_TOO_LONG: 'ERROR_TITLE_TOO_LONG',
  ERROR_SUBTITLE_TOO_LONG: 'ERROR_SUBTITLE_TOO_LONG',
  ERROR_EMPTY_ITEMS_LIST: 'ERROR_EMPTY_ITEMS_LIST',
  ERROR_ITEM_ALREADY_IN_PROGRESS: 'ERROR_ITEM_ALREADY_IN_PROGRESS',
  ERROR_ITEM_ALREADY_DONE: 'ERROR_ITEM_ALREADY_DONE',
  ERROR_SENDING_EMAIL: 'ERROR_SENDING_EMAIL',
  ERROR_INVALID_ACCESS_TOKEN: 'ERROR_INVALID_ACCESS_TOKEN',
  ERROR_TEXT_TOO_SHORT: 'ERROR_TEXT_TOO_SHORT',
}

export const STAGES = {
  DEV: 'DEV',
  PROD: 'PROD',
}

export const MAX_TITLE_LENGTH = 128
export const MAX_QR_TITLE_LENGTH = 25
export const MAX_QR_SUBTITLE_LENGTH = 100
